### ISSUE TITLE
Add example for installing a cargo subcommand.

### ISSUE THREAD

**Issue by dvc94ch** [actions-rs/example#11]
There seems to be some support for caching the subcommand, and just running `cargo install` manually doesn't install it to a location that is on the `PATH`.

**Comment by svartalf** [comment]
Hi, @dvc94ch! Can you elaborate more on this issue?

`~/.cargo/bin` [should be added](https://github.com/actions-rs/core/blob/949cd9e5aeccf71592a43f6ddc31fca15fccb06c/src/commands/rustup.ts#L88
) into the `PATH` during the [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) execution, so as long as you are using it, any `cargo install`-ed binary will be available in your `PATH`.

Yet, proper caching of the installed binary is not implemented yet, see https://github.com/actions-rs/meta/issues/21

EDIT: here is a wild example of `cargo install cargo-nono` and the following call of it: https://github.com/svartalf/rust-macaddr/runs/371402468

**Comment by dvc94ch** [comment]
Looks like I made a mistake. It seems that it was missing a tool that the cargo subcommand needed.
